# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3fbced7135bd1095db2e1673332b6a631c3c709dc9125fd9570ce8af41094e379800d16bdb13488fc9808b69ff8cc24dae29377f0b503a6eba7d0554418af1c
  devise_secret_key: fd30d50004d2779b7c8742863706c15398ecf0417e4d80041daeeb5c63ac49d6c42efaba6d1e739cf945d327ca38259fd538d9b72fad6e19c9910948a12cdba8
  build_api_token: 'theToken'

test:
  secret_key_base: 2ba476a330cc6c0e18c0e084b9678bd5b7f5c53a22f7823e82abf7584b60b541d65da4198d3d7378c05b5d35c2e92bdcf7ffaaa276c6737faff39839e702690c
  devise_secret_key: fd30d50004d2779b7c8742863706c15398ecf0417e4d80041daeeb5c63ac49d6c42efaba6d1e739cf945d327ca38259fd538d9b72fad6e19c9910948a12cdba8
  build_api_token: 'theToken'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  build_api_token: <%= ENV["BUILD_API_KEY"] %>
